export const ROOT = 'Root'
export const DIRECTORY = 'Directory'
export const DIRECTORYINFO = 'DirectoryInfo'
export const SITUATIONSELECT = 'SituationSelect'
export const MENTALSELECT = 'MentalSelect'
export const PHYSICALSELECT = 'PhysicalSelect'
export const RESOURCESELECTMENTAL = 'ResourceSelectMental'
export const RESOURCESELECTPHYSICAL = 'ResourceSelectPhysical'
